[package]
name = "no-modules"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.82"

[lib]
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3.59"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]